#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
title: Maggie's Blog 
# Short bio or description (displayed in the header)
description: This is Maggie's (Margaret) blog for her ENGL 460 class. This is an exercise in the use of Jekyll.
#
# !! DON'T EDIT BELOW THIS MESSAGE
#
# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-modernist